spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    producer:
      keySerializer: "mk.ukim.finki.thesis.common.serializer.MessageKeySerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
kafka:
  topic:
    producer-one:
      user-actions: "mk.ukim.finki.thesis.producer-one.user-actions"